AES_KEY=uG1w6s0ZzXgE6Zx4xq9D0w==
current.ltfs.drive= E:
document.storage.base.path=C:/FTP
document.storage.path=${document.storage.base.path}/DMS_Document
ProfileStoragePath=${document.storage.base.path}/DMS_Document/profile
waitingroom.storage.path=${document.storage.base.path}/WaitingRoom
spring.datasource.url=jdbc:mysql://103.133.215.182:3306/dms?&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/dms?&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false

spring.datasource.username=dms
spring.datasource.password=DMS123
app.lto.restored.retention-days=30

#Scheduled time
# run every 1 minute
scheduled.waitingroom.time=60000

# run every day at midnight (00:00)
scheduled.archive.time=0 0 0 * * ?

# run every day at midnight (00:00)
scheduled.clean.time=0 0 0 * * ?


# ===============================
# LTO ARCHIVE CONFIG
# ===============================

lto.delete.mode=AFTER_TRANSFER
# OPTIONS
# AFTER_TRANSFER
# AFTER_DAYS
# NEVER

lto.delete.after.days=7

archive.retry.max-attempts=3

archive.parallel.threads=2

lto.verify.checksum=true