package com.dmsBackend.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;

@Data
@NoArgsConstructor
public class EmployeeResponse {
    private int id;
    private String name;
    private String branchName;
    private String departmentName;
    private String roleName;
    private String status;
    private Timestamp createDate;
    private String mobile;
    private String email;

    // Constructor with parameters
    public EmployeeResponse(int id, String name, String branchName, String departmentName,
                            String roleName, String status, Timestamp createDate,
                            String mobile, String email) {
        this.id = id;
        this.name = name;
        this.branchName = branchName;
        this.departmentName = departmentName;
        this.roleName = roleName;
        this.status = status;
        this.createDate = createDate;
        this.mobile = mobile;
        this.email = email;
    }

    // Getters and Setters (generated by Lombok or manually)
}
